In [1]:
import pandas as pd

In [2]:
# reading csv file
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Adding a new column

## 1.1 Adding a new column with a scalar value

In [5]:
# adding new column to a dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,language score
0,female,group B,bachelor,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master,standard,none,90,95,93,70
3,male,group A,associate,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
5,female,group B,associate,standard,none,71,83,78,70
6,female,group B,some college,standard,none,88,95,92,70

## 1.2 Adding a new column with an array

#### the dataframehas 7 rows, so we need to create an array with 7 elements

In [7]:
import numpy as np

In [12]:
# create an array of 7 elements
language_score = np.arange(0,7)

In [13]:
# length of the array
len(language_score)

7

In [15]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,language score
0,female,group B,bachelor,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master,standard,none,90,95,93,2
3,male,group A,associate,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
5,female,group B,associate,standard,none,71,83,78,5
6,female,group B,some college,standard,none,88,95,92,6

In [17]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1,100, size=7)

In [19]:
# min vlaue inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

72

In [21]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,language score
0,female,group B,bachelor,standard,none,72,72,74,26
1,female,group C,some college,standard,completed,69,90,88,72
2,female,group B,master,standard,none,90,95,93,64
3,male,group A,associate,free/reduced,none,47,57,44,45
4,male,group C,some college,standard,none,76,78,75,19
5,female,group B,associate,standard,none,71,83,78,31
6,female,group B,some college,standard,none,88,95,92,10

In [25]:
# create random fat numbers between 1 and 100
float_language_score = np.random.uniform(1,100, size=7)

In [26]:
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,language score
0,female,group B,bachelor,standard,none,72,72,74,26
1,female,group C,some college,standard,completed,69,90,88,72
2,female,group B,master,standard,none,90,95,93,64
3,male,group A,associate,free/reduced,none,47,57,44,45
4,male,group C,some college,standard,none,76,78,75,19
5,female,group B,associate,standard,none,71,83,78,31
6,female,group B,some college,standard,none,88,95,92,10