In [47]:
import pandas as pd

In [48]:
# reading csv
df_cars = pd.read_csv('Car_sales.csv')
df_cars

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [49]:
df_cars['Vehicle_type'].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [50]:
# selecting columns
df_cars = df_cars[['Manufacturer','Sales_in_thousands',
         'Vehicle_type','Price_in_thousands', 
         'Engine_size','Horsepower','Fuel_capacity']]

In [51]:
# show dataframe
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [52]:
# calculate number of unique values
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

# 1 agg()

In [53]:
# calculate the sum of columns
df_cars_sample = df_cars[['Sales_in_thousands',
                          'Price_in_thousands', 
         'Engine_size','Horsepower','Fuel_capacity']]
df_cars_sample.agg('sum')

Sales_in_thousands     8320.698
Price_in_thousands     4245.567
Engine_size             477.500
Horsepower            29008.000
Fuel_capacity          2800.500
dtype: float64

In [54]:
# calculate the mean of numeric columns
df_cars_sample.agg('mean')

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [55]:
# calculate the mean and count values
df_cars_sample.agg(['mean','count'])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
count,157.000000,155.000000,156.000000,156.000000,156.000000

In [56]:
# Different aggregations per column: calculate the sum and mean of 'Sales_in_thousands'
# and sum and max of 'Price_in_thousands'
df_cars_sample.agg({'Sales_in_thousands':['sum', 'mean'],
                    'Price_in_thousands':['sum','max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [57]:
# aggregate over (along) the columns
df_cars_sample[['Sales_in_thousands','Price_in_thousands']].agg('sum', axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [58]:
# equivalent (NaN behaves differently)
df_cars_sample['Sales_in_thousands'] + df_cars_sample['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

Note: agg() treats NaN as zero

In [59]:
# aggregate different functions and 
# rename the index of the resulting dataframe
df_cars_sample.agg(x = ('Sales_in_thousands','sum'),
                   y = ('Price_in_thousands','sum'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

# 2 The Split-Apply-Combine Strategy

In [60]:
# split data into separate groups

passenger_filter = df_cars['Vehicle_type']=='Passenger'
car_filter = df_cars['Vehicle_type']=='Car'

#df_cars['Vehicle_type'].value_counts()

In [61]:
# apply an operation
passenger_average = df_cars[passenger_filter]['Sales_in_thousands'].mean()
car_average = df_cars[car_filter]['Sales_in_thousands'].mean()

In [62]:
# combine results
pd.DataFrame({'Vehicle_type':['Car','Passenger'],
              'Sales_in_thousands':[passenger_average,car_average]})

  Vehicle_type  Sales_in_thousands
0          Car           43.234345
1    Passenger           80.622293

# 3 groupby()

In [63]:
# group by Vehicle_type and calculate the mean
df_cars.groupby('Vehicle_type').mean()

TypeError: agg function failed [how->mean,dtype->object]

In [67]:
# group by Manufacturer
groupby_obj = df_cars.groupby('Manufacturer')

In [65]:
# the groupby_obj
groupby_obj

In [69]:
# groups attribute and keys
groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [71]:
groupby_obj.groups

{'Acura': [0, 1, 2, 3], 'Audi': [4, 5, 6], 'BMW': [7, 8, 9], 'Buick': [10, 11, 12, 13], 'Cadillac': [14, 15, 16, 17, 18], 'Chevrolet': [19, 20, 21, 22, 23, 24, 25, 26, 27], 'Chrysler': [28, 29, 30, 31, 32, 33, 34], 'Dodge': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], 'Ford': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], 'Honda': [57, 58, 59, 60, 61], 'Hyundai': [62, 63, 64], 'Infiniti': [65], 'Jaguar': [66], 'Jeep': [67, 68, 69], 'Lexus': [70, 71, 72, 73, 74, 75], 'Lincoln': [76, 77, 78], 'Mercedes-B': [92, 93, 94, 95, 96, 97, 98, 99, 100], 'Mercury': [86, 87, 88, 89, 90, 91], 'Mitsubishi': [79, 80, 81, 82, 83, 84, 85], 'Nissan': [101, 102, 103, 104, 105, 106, 107], 'Oldsmobile': [108, 109, 110, 111, 112, 113], 'Plymouth': [114, 115, 116, 117], 'Pontiac': [118, 119, 120, 121, 122, 123], 'Porsche': [124, 125, 126], 'Saab': [127, 128], 'Saturn': [129, 130, 131, 132, 133], 'Subaru': [134, 135], 'Toyota': [136, 137, 138, 139, 140, 141, 142, 143, 144], 'Volkswagen': [145, 146, 147, 148, 149, 150], 'Volvo': [151, 152, 153, 154, 155, 156]}

In [70]:
# get a specific group within the Manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [80]:
# group by Manufacturer and calculate the mean
df_cars.groupby('Manufacturer').mean().head()

TypeError: agg function failed [how->mean,dtype->object]

In [81]:
# group by Manufacturer and calculate the sum
df_cars.groupby('Manufacturer').sum().head()

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,,
Acura,79.005,PassengerPassengerPassengerPassenger,91.900,11.7,800.0,65.6
Audi,40.557,PassengerPassengerPassenger,119.940,8.8,660.0,58.6
BMW,46.505,PassengerPassengerPassenger,99.290,8.1,556.0,51.7
Buick,242.019,PassengerPassengerPassengerPassenger,107.125,14.5,825.0,71.0
Cadillac,112.178,PassengerPassengerPassengerPassengerCar,201.270,22.5,1280.0,104.0

In [82]:
# group by Vehicle_type and count values
df_cars.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [83]:
# find null values in columns
df_cars.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [85]:
# group by Engine_size and count values without dropping NaN values
df_cars.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

# 4 Groupby() and agg()

In [90]:
# find the minimum and maximum values on each column
df_cars.groupby('Vehicle_type').min()
df_cars.groupby('Vehicle_type').max()
df_cars.groupby('Vehicle_type').agg(['min','max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [92]:
# set a name for aggregated column
# find the min Engine_size and max Horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size', 'min'),
                                    max_horsepower=('Horsepower', 'max'))

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [94]:
# calculate the sum of Sales_in_thousands and mean of Price_in_thousands
df_cars.groupby('Manufacturer').agg(sum_sales = ('Sales_in_thousands','sum'),
                                   mean_price = ('Price_in_thousands','mean'))

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000
Chevrolet       554.365   20.022778
Chrysler        201.721   23.430833
Dodge           910.149   24.213636
Ford           2022.635   21.047273
Honda           592.674   20.277000
Hyundai         137.326   12.165667
Infiniti         23.713   29.465000
Jaguar           15.467   42.800000
Jeep            293.153   20.991667
Lexus           106.843   44.055000
Lincoln          85.634   41.690000
Mercedes-B      117.125   52.916667
Mercury         237.999   20.748333
Mitsubishi      180.895   22.167429
Nissan          399.635   22.360714
Oldsmobile      178.989   25.622833
Plymouth         64.001   22.642500
Pontiac         370.534   22.949167
Porsche          12.128   62.473333
Saab             21.306   29.610000
Saturn          168.850   14.271000
Subaru           80.135   21.395000
Toyota          740.205   21.982889
Volkswagen      209.212   17.698333
Volvo            75.740   30.933333

In [96]:
df_cars.groupby('Manufacturer').sum()['Sales_in_thousands']

Manufacturer
Acura           79.005
Audi            40.557
BMW             46.505
Buick          242.019
Cadillac       112.178
Chevrolet      554.365
Chrysler       201.721
Dodge          910.149
Ford          2022.635
Honda          592.674
Hyundai        137.326
Infiniti        23.713
Jaguar          15.467
Jeep           293.153
Lexus          106.843
Lincoln         85.634
Mercedes-B     117.125
Mercury        237.999
Mitsubishi     180.895
Nissan         399.635
Oldsmobile     178.989
Plymouth        64.001
Pontiac        370.534
Porsche         12.128
Saab            21.306
Saturn         168.850
Subaru          80.135
Toyota         740.205
Volkswagen     209.212
Volvo           75.740
Name: Sales_in_thousands, dtype: float64

In [99]:
df_cars.groupby('Manufacturer').mean()['Price_in_thousands']

TypeError: agg function failed [how->mean,dtype->object]

# 5 Lambda

apply your own function

In [103]:
df_cars.groupby('Manufacturer').sum().head()

,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,,
Acura,79.005,PassengerPassengerPassengerPassenger,91.900,11.7,800.0,65.6
Audi,40.557,PassengerPassengerPassenger,119.940,8.8,660.0,58.6
BMW,46.505,PassengerPassengerPassenger,99.290,8.1,556.0,51.7
Buick,242.019,PassengerPassengerPassengerPassenger,107.125,14.5,825.0,71.0
Cadillac,112.178,PassengerPassengerPassengerPassengerCar,201.270,22.5,1280.0,104.0

In [104]:
sum_one = lambda x:x+1
sum_one(1)

2

In [106]:
# get actual sales and price values
df_cars.groupby('Manufacturer').sum().apply(lambda x:x*1000)[['Sales_in_thousands','Price_in_thousands']]

              Sales_in_thousands  Price_in_thousands
Manufacturer
Acura                    79005.0             91900.0
Audi                     40557.0            119940.0
BMW                      46505.0             99290.0
Buick                   242019.0            107125.0
Cadillac                112178.0            201270.0
Chevrolet               554365.0            180205.0
Chrysler                201721.0            140585.0
Dodge                   910149.0            266350.0
Ford                   2022635.0            231520.0
Honda                   592674.0            101385.0
Hyundai                 137326.0             36497.0
Infiniti                 23713.0             29465.0
Jaguar                   15467.0             42800.0
Jeep                    293153.0             62975.0
Lexus                   106843.0            264330.0
Lincoln                  85634.0            125070.0
Mercedes-B              117125.0            476250.0
Mercury                 237999.0            124490.0
Mitsubishi              180895.0            155172.0
Nissan                  399635.0            156525.0
Oldsmobile              178989.0            153737.0
Plymouth                 64001.0             90570.0
Pontiac                 370534.0            137695.0
Porsche                  12128.0            187420.0
Saab                     21306.0             59220.0
Saturn                  168850.0             71355.0
Subaru                   80135.0             42790.0
Toyota                  740205.0            197846.0
Volkswagen              209212.0            106190.0
Volvo                    75740.0            185600.0

In [110]:
# subtract values from the mean of each group
df_cars_sample2 = df_cars[['Manufacturer','Sales_in_thousands',
                          'Price_in_thousands', 
         'Engine_size','Horsepower','Fuel_capacity']]
df_cars_sample2.groupby('Manufacturer').apply(lambda x:x-x.mean())

                  Sales_in_thousands  Price_in_thousands  Engine_size  \
Manufacturer
Acura        0             -2.832250           -9.133333    -1.125000
             1             19.632750           -2.233333     0.275000
             2             -5.637250                 NaN     0.275000
             3            -11.163250           11.366667     0.575000
Audi         4              6.878000          -15.990000    -1.133333
...                              ...                 ...          ...
Volvo        152           -9.078333           -6.533333    -0.400000
             153            2.621667           -3.433333     0.100000
             154            4.907667           -2.133333     0.100000
             155           -9.130333           14.566667     0.000000
             156            6.345667            5.066667     0.600000

                  Horsepower  Fuel_capacity
Manufacturer
Acura        0    -60.000000      -3.200000
             1     25.000000       0.800000
             2     25.000000       0.800000
             3     10.000000       1.600000
Audi         4    -70.000000      -3.133333
...                      ...            ...
Volvo        152  -22.166667      -2.033333
             153  -14.166667       0.066667
             154  -14.166667       0.066667
             155   53.833333       0.666667
             156   18.833333       3.266667

[157 rows x 5 columns]

In [112]:
df_cars.groupby('Manufacturer').mean()

TypeError: agg function failed [how->mean,dtype->object]

# 6 The filter() method

In [114]:
# calculate the mean of Sales_in_thousands

In [117]:
df_cars_sample.mean()

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [118]:
# filter certain values out based on sum() and return a subset
def filter_func(x):
    return x['Sales_in_thousands'].sum() > 52

df_filter = df_cars.groupby(['Manufacturer']).filter(filter_func)

In [119]:
df_filter

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1

In [123]:
df_cars.groupby(['Manufacturer']).sum()['Sales_in_thousands'].sort_values().head(6)

Manufacturer
Porsche     12.128
Jaguar      15.467
Saab        21.306
Infiniti    23.713
Audi        40.557
BMW         46.505
Name: Sales_in_thousands, dtype: float64

In [126]:
df_cars[df_cars['Manufacturer'].isin(['Porsche', 'Jaguar', 'Saab', 'Infiniti', 'Audi', 'BMW'])].shape

(13, 7)

In [127]:
df_cars.shape

(157, 7)

In [128]:
df_filter.shape

(144, 7)