In [1]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv('StudentPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score
0,female,group B,bachelor,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master,standard,none,90,95,93
3,male,group A,associate,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 1 Math Operations

## 1.1 Operations in columns

In [4]:
# Select a column and calculate total sum
df_exams['math score'].sum()

513

In [9]:
# count, mean, std, max, and min
print("count: ", df_exams['math score'].count())
print("mean: ",df_exams['math score'].mean())
print("std: ",df_exams['math score'].std())
print("max: ",df_exams['math score'].max())
print("min: ",df_exams['math score'].min())

count:  7
mean:  73.28571428571429
std:  14.25615990504088
max:  90
min:  47

In [11]:
# easier calculation with .describe()
df_exams.describe()

       math score  reading score  writing score
count    7.000000       7.000000       7.000000
mean    73.285714      81.428571      77.714286
std     14.256160      13.794409      16.839579
min     47.000000      57.000000      44.000000
25%     70.000000      75.000000      74.500000
50%     72.000000      83.000000      78.000000
75%     82.000000      92.500000      90.000000
max     90.000000      95.000000      93.000000

## 1.2 Operations in rows

In [12]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0    218
1    247
2    278
3    148
4    229
5    232
6    275
dtype: int64

In [15]:
# calculating the average score & assigning result to new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [17]:
# showing the dataframe
df_exams.round(2)

,gender,race/ethnicity,parental leave,lunch,test preparation,math score,reading score,writing score,average
0,female,group B,bachelor,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master,standard,none,90,95,93,92.67
3,male,group A,associate,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
5,female,group B,associate,standard,none,71,83,78,77.33
6,female,group B,some college,standard,none,88,95,92,91.67