In [2]:
import pandas as pd

# 1 Read a csv from a URL with Pandas

Target website: https://football-data.co.uk/data.php

In [3]:
# reading single csv file from the website
df_premier21 = pd.read_csv('https://football-data.co.uk/mmz4281/2122/E0.csv')

In [3]:
# showing dataframe
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [4]:
# rename columns
df_premier21.rename(columns={'FTHG': 'home_goals',
                             'FTAG': 'away_goals'}, inplace=True)

In [5]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

# 2 Read CSV from Multiple URLs w/ Pandas

Link: root + season + league

https://football-data.co.uk/mmz4281/2425/E0.csv

In [6]:
# Link structure
"https://football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2122/E0.csv'

In [7]:
# create a root variable
root = "https://football-data.co.uk/mmz4281/"

## 2.1 Multiple Leagues

In [9]:
# creating list of Leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
# empty list
frames = []

# looping through Leagues, read mulitple csv & append it into a list
for league in leagues:
    df = pd.read_csv(root + '2122/' + league + '.csv', encoding='unicode_escape')
    # store all dataframes in frames list, b/c in each iteration df refreshes
    frames.append(df)

In [10]:
# length of frames
len(frames)

5

In [13]:
# show 1st, 2nd, 3rd element
#frames[0]
# frames[1]
frames[2]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,07/08/2021,15:00,Bolton,Milton Keynes Dons,3,3,D,1,1,...,1.97,-0.25,1.90,1.95,1.91,1.97,1.99,2.01,1.90,1.92
1,E2,07/08/2021,15:00,Cambridge,Oxford,1,1,D,0,1,...,1.86,0.25,2.08,1.73,2.12,1.78,2.12,1.82,2.06,1.77
2,E2,07/08/2021,15:00,Crewe,Cheltenham,1,1,D,1,1,...,1.69,-0.25,2.00,1.85,1.99,1.90,2.04,1.95,1.96,1.87
3,E2,07/08/2021,15:00,Doncaster,AFC Wimbledon,1,2,A,0,0,...,1.88,-0.25,2.10,1.77,2.11,1.80,2.12,1.82,2.07,1.77
4,E2,07/08/2021,15:00,Fleetwood Town,Portsmouth,0,1,A,0,0,...,1.60,0.00,2.05,1.80,2.09,1.82,2.13,1.86,2.07,1.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,30/04/2022,12:30,Morecambe,Sunderland,0,1,A,0,1,...,2.09,0.75,2.05,1.80,2.05,1.84,2.09,1.86,2.02,1.81
548,E2,30/04/2022,12:30,Oxford,Doncaster,1,1,D,1,0,...,3.05,-1.50,1.90,1.95,1.96,1.93,2.00,1.99,1.92,1.88
549,E2,30/04/2022,12:30,Plymouth,Milton Keynes Dons,0,5,A,0,3,...,1.94,0.25,1.83,2.02,1.81,2.09,1.88,2.09,1.81,2.02
550,E2,30/04/2022,12:30,Sheffield Weds,Portsmouth,4,1,H,3,1,...,2.04,-1.00,1.73,2.15,1.76,2.14,1.90,2.21,1.77,2.07
551,E2,30/04/2022,12:30,Shrewsbury,Wigan,0,3,A,0,1,...,1.73,0.50,1.95,1.90,1.97,1.92,2.02,1.94,1.94,1.87

## 2.2 Multiple Seasons

In [14]:
# creating list of Leagues
leagues = ['E0', 'E2','E3']
# empty list
frames = []

# loop through range of seasons and insert new column
for league in leagues:
    # seasons 2015-2020
    for season in range(15, 21):
        df = pd.read_csv( root + str(season) + str(season+1) + '/' + league + '.csv')
        
        # adding season column for each dataframe
        df.insert(1, 'season', season)
        
        # store all dataframes in frames list, b/c in each iteration df refreshes
        frames.append(df)

In [18]:
# total frames (6 seasons x 3 leagues)
len(frames)

18

In [20]:
# show 1st & last element (new season column was created)
print(frames[0])
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print(frames[17])

    Div  season        Date     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0    E0      15  08/08/2015  Bournemouth  Aston Villa     0     1   A     0
1    E0      15  08/08/2015      Chelsea      Swansea     2     2   D     2
2    E0      15  08/08/2015      Everton      Watford     2     2   D     0
3    E0      15  08/08/2015    Leicester   Sunderland     4     2   H     3
4    E0      15  08/08/2015   Man United    Tottenham     1     0   H     1
..   ..     ...         ...          ...          ...   ...   ...  ..   ...
375  E0      15  15/05/2016        Stoke     West Ham     2     1   H     0
376  E0      15  15/05/2016      Swansea     Man City     1     1   D     1
377  E0      15  15/05/2016      Watford   Sunderland     2     2   D     0
378  E0      15  15/05/2016    West Brom    Liverpool     1     1   D     1
379  E0      15  17/05/2016   Man United  Bournemouth     3     1   H     1

     HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  \
0       0  ...     1.79   26  -0.50     1.98     1.93     1.99     1.92  1.82
1       1  ...     1.99   27  -1.50     2.24     2.16     1.80     1.73  1.37
2       1  ...     1.96   26  -1.00     2.28     2.18     1.76     1.71  1.75
3       0  ...     1.67   26  -0.50     2.00     1.95     1.96     1.90  1.79
4       0  ...     2.01   26  -1.00     2.20     2.09     1.82     1.78  1.64
..    ...  ...      ...  ...    ...      ...      ...      ...      ...   ...
375     1  ...     2.27   30   0.25     2.11     2.03     1.87     1.83  3.05
376     1  ...     2.45   31   1.00     2.14     2.05     1.85     1.81  7.05
377     1  ...     2.10   29  -0.50     2.06     2.01     1.91     1.85  1.64
378     1  ...     2.09   30  -0.25     2.10     2.05     1.86     1.81  2.61
379     0  ...     2.20   29  -0.75     1.88     1.84     2.08     2.02  1.50

     PSCD   PSCA
0    3.88   4.70
1    5.04  10.88
2    3.76   5.44
3    3.74   5.10
4    4.07   6.04
..    ...    ...
375  4.00   2.26
376  5.00   1.47
377  4.52   5.27
378  3.75   2.70
379  4.60   7.03

[380 rows x 66 columns]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Div  season        Date   Time    HomeTeam        AwayTeam  FTHG  FTAG  \
0    E3      20  12/09/2020  15:00      Barrow       Stevenage     1     1
1    E3      20  12/09/2020  15:00      Bolton    Forest Green     0     1
2    E3      20  12/09/2020  15:00    Bradford      Colchester     0     0
3    E3      20  12/09/2020  15:00   Cambridge        Carlisle     3     0
4    E3      20  12/09/2020  15:00  Cheltenham       Morecambe     1     2
..   ..     ...         ...    ...         ...             ...   ...   ...
547  E3      20  08/05/2021  15:00   Port Vale       Mansfield     0     3
548  E3      20  08/05/2021  15:00  Scunthorpe       Stevenage     0     1
549  E3      20  08/05/2021  15:00    Southend  Newport County     1     1
550  E3      20  08/05/2021  15:00    Tranmere      Colchester     0     0
551  E3      20  08/05/2021  16:00     Salford   Leyton Orient     3     0

    FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  MaxCAHH  \
0     D     1  ...      1.76 -0.25     1.95      1.90   1.93   1.98     1.98
1     A     0  ...      1.79 -0.25     2.02      1.83   2.04   1.87     2.09
2     D     0  ...      1.65 -0.25     2.07      1.72   2.11   1.82     2.20
3     H     2  ...      1.70 -0.25     1.98      1.88   2.02   1.88     2.04
4     A     1  ...      1.75 -0.50     1.83      2.02   1.87   2.04     1.88
..   ..   ...  ...       ...   ...      ...       ...    ...    ...      ...
547   A     0  ...      1.84  0.25     1.90      1.95   1.89   2.00     1.95
548   A     0  ...      1.73  0.50     1.80      2.05   1.84   2.06     1.87
549   D     1  ...      1.44  0.50     1.93      1.93   1.94   1.94     1.97
550   D     0  ...      1.59 -0.75     2.05      1.80   2.05   1.85     2.08
551   H     1  ...      1.87 -1.00     1.98      1.88   1.99   1.90     2.01

     MaxCAHA  AvgCAHH  AvgCAHA
0       1.99     1.91     1.92
1       1.90     2.00     1.83
2       1.82     2.09     1.76
3       1.90     1.99     1.84
4       2.09     1.83     2.00
..       ...      ...      ...
547     2.07     1.85     1.97
548     2.14     1.77     2.07
549     1.97     1.91     1.91
550     1.89     2.01     1.82
551     1.96     1.96     1.86

[552 rows x 107 columns]

# 3 Organize All the Data in a Dictionary

In [22]:
# create a dictionary with original name of league as key
dict_countries = {'Spanish La Liga':'SP1', 'Spanish Segundo Division':'SP2',
                 'German Bundesliga':'D1',
                 'English Premier League': 'E0', 'English League 1': 'E2', 'English League 2':'E3'}

In [24]:
# get a dictionary element
dict_countries['Spanish La Liga']

'SP1'

In [29]:
for league in dict_countries:
    print(league, '-' ,dict_countries[league])

Spanish La Liga - SP1
Spanish Segundo Division - SP2
German Bundesliga - D1
English Premier League - E0
English League 1 - E2
English League 2 - E3

In [32]:
dict_historical_data = {}

# creating list of Leagues
#leagues = ['E0', 'E2','E3']
# empty list
#frames = [] placing this inside the for loop so that 
#            the list doesn't contain older data after every iteration

# looping through key elements
for league in dict_countries:
    frames = []
    # seasons 2015-2020
    for season in range(15, 21):
        df = pd.read_csv( root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        
        # adding season column for each dataframe
        df.insert(1, 'season', season)
        
        # store all dataframes in frames list, b/c in each iteration df refreshes
        frames.append(df)
    df_concat = pd.concat(frames)
    # df_concat is the value which contains all the dataframes from season 15-20, league is the key
    dict_historical_data[league] = df_concat

In [34]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segundo Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [35]:
# show dataframe inside dict_historical_data
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88